sensor:
  - platform: template
    sensors:
      fenster_buero:
        value_template: '{% if states.binary_sensor.fenster_buero %}
          {% if states.binary_sensor.fenster_buero.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Fenster Büro'

      tuer_buero:
        value_template: '{% if states.binary_sensor.tuer_buero %}
          {% if states.binary_sensor.tuer_buero.state == "on" %}
            offen
          {% else %}
            geschlossen
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
        friendly_name: 'Tür Büro'

media_player:
  - platform: yamaha_musiccast
    host: !secret yamaha_ip